;
; File generated by co65 v 2.18 - Git c59e8277 using model 'none'
;
.fopt		compiler,"co65 v 2.18 - Git c59e8277"
.case		on
.debuginfo	off

_ijk_detect = CODE+0
.export	_ijk_detect
ijk_detect = CODE+40
.export	ijk_detect
_ijk_read = CODE+3
.export	_ijk_read
ijk_read = CODE+92
.export	ijk_read
_ijk_present = CODE+6
.export	_ijk_present
_ijk_ljoy = CODE+7
.export	_ijk_ljoy
_ijk_rjoy = CODE+8
.export	_ijk_rjoy
ijk_prepare = CODE+9
.export	ijk_prepare
ijk_release = CODE+31
.export	ijk_release

;
; CODE SEGMENT
;
.segment	"CODE"
CODE:
	.byte	$4C
	.word	CODE+40
	.byte	$4C
	.word	CODE+92
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$AD
	.byte	$02
	.byte	$03
	.byte	$09
	.byte	$10
	.byte	$8D
	.byte	$02
	.byte	$03
	.byte	$AD
	.byte	$00
	.byte	$03
	.byte	$29
	.byte	$EF
	.byte	$8D
	.byte	$00
	.byte	$03
	.byte	$A9
	.byte	$C0
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$60
	.byte	$AD
	.byte	$00
	.byte	$03
	.byte	$09
	.byte	$10
	.byte	$8D
	.byte	$00
	.byte	$03
	.byte	$60
	.byte	$08
	.byte	$78
	.byte	$AD
	.byte	$03
	.byte	$03
	.byte	$48
	.byte	$AD
	.byte	$01
	.byte	$03
	.byte	$48
	.byte	$A9
	.byte	$00
	.byte	$8D
	.word	CODE+6
	.byte	$8D
	.word	CODE+7
	.byte	$8D
	.word	CODE+8
	.byte	$20
	.word	CODE+9
	.byte	$A9
	.byte	$C0
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$AD
	.byte	$0F
	.byte	$03
	.byte	$29
	.byte	$20
	.byte	$49
	.byte	$20
	.byte	$8D
	.word	CODE+6
	.byte	$20
	.word	CODE+31
	.byte	$68
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$68
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$28
	.byte	$60
	.byte	$08
	.byte	$78
	.byte	$AD
	.byte	$03
	.byte	$03
	.byte	$48
	.byte	$AD
	.byte	$01
	.byte	$03
	.byte	$48
	.byte	$20
	.word	CODE+9
	.byte	$A9
	.byte	$40
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$AD
	.byte	$0F
	.byte	$03
	.byte	$29
	.byte	$1F
	.byte	$49
	.byte	$1F
	.byte	$8D
	.word	CODE+7
	.byte	$A9
	.byte	$80
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$AD
	.byte	$0F
	.byte	$03
	.byte	$29
	.byte	$1F
	.byte	$49
	.byte	$1F
	.byte	$8D
	.word	CODE+8
	.byte	$20
	.word	CODE+31
	.byte	$68
	.byte	$8D
	.byte	$0F
	.byte	$03
	.byte	$68
	.byte	$8D
	.byte	$03
	.byte	$03
	.byte	$28
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.segment	"ZEROPAGE": zeropage
ZEROPAGE:
	.res	0

.end
