;
; File generated by co65 v 2.19 - Git bf9d4ac3 using model 'cc65-module'
;
.fopt		compiler,"co65 v 2.19 - Git bf9d4ac3"
.case		on
.debuginfo	off
.export		_telestratjoy

;
; CODE SEGMENT
;
.segment	"CODE"
_telestratjoy:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$05
	.byte	$00
	.byte	$00
	.word	_telestratjoy+14
	.word	_telestratjoy+26
	.word	_telestratjoy+27
	.word	_telestratjoy+32
	.byte	$A9
	.byte	$C0
	.byte	$8D
	.byte	$22
	.byte	$03
	.byte	$8D
	.byte	$20
	.byte	$03
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$02
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$F0
	.byte	$10
	.byte	$AD
	.byte	$20
	.byte	$03
	.byte	$29
	.byte	$7F
	.byte	$09
	.byte	$40
	.byte	$8D
	.byte	$20
	.byte	$03
	.byte	$AD
	.byte	$20
	.byte	$03
	.byte	$49
	.byte	$5F
	.byte	$60
	.byte	$AD
	.byte	$20
	.byte	$03
	.byte	$29
	.byte	$BF
	.byte	$09
	.byte	$80
	.byte	$8D
	.byte	$20
	.byte	$03
	.byte	$AD
	.byte	$20
	.byte	$03
	.byte	$49
	.byte	$9F
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
