//
//	This file was generated by the GEOS Resource Compiler
//
//	DO NOT EDIT! Any changes will be lost!
//
//	Edit proper resource file instead.
//

extern void _OVERLAYADDR__[];
extern void _OVERLAYSIZE__[];

#define OVERLAY_ADDR (char*)   _OVERLAYADDR__
#define OVERLAY_SIZE (unsigned)_OVERLAYSIZE__

